export const sampleCertificates = [
  {
    id: 1,
    code: "CERT001",
    carat: 1.2,
    clarity: "VVS1",
    color: "D",
    cut: "Round",
    flourescence: "None",
    make: "Excellent",
    polish: "Excellent",
    symmetry: "Excellent",
    measurement: "6.5 - 6.5 x 4.0 mm",
    cert: "GIA",
    min_price: 5000,
    max_price: 6000,
    rap_percent: 10.5,
    rap_price: 5500,
    real_price: 5750,
    name: "GIA",
  },
  {
    id: 2,
    code: "CERT002",
    carat: 1.5,
    clarity: "VS2",
    color: "E",
    cut: "Princess",
    flourescence: "Medium",
    make: "Very Good",
    polish: "Excellent",
    symmetry: "Very Good",
    measurement: "7.0 - 7.0 x 4.5 mm",
    cert: "IGI",
    min_price: 7000,
    max_price: 8000,
    rap_percent: 11.0,
    rap_price: 7500,
    real_price: 7800,
    name: "IGI",
  },
  {
    id: 3,
    code: "CERT003",
    carat: 0.9,
    clarity: "SI1",
    color: "F",
    cut: "Oval",
    flourescence: "Strong",
    make: "Good",
    polish: "Very Good",
    symmetry: "Good",
    measurement: "6.0 - 4.0 x 3.5 mm",
    cert: "HRD",
    min_price: 3000,
    max_price: 3500,
    rap_percent: 8.0,
    rap_price: 3200,
    real_price: 3350,
    name: "HRD",
  },
  {
    id: 4,
    code: "CERT004",
    carat: 2.0,
    clarity: "IF",
    color: "G",
    cut: "Emerald",
    flourescence: "None",
    make: "Excellent",
    polish: "Excellent",
    symmetry: "Excellent",
    measurement: "8.0 - 8.0 x 5.0 mm",
    cert: "GIA",
    min_price: 15000,
    max_price: 17000,
    rap_percent: 12.5,
    rap_price: 16000,
    real_price: 16500,
    name: "GIA",
  },
  {
    id: 5,
    code: "CERT005",
    carat: 1.1,
    clarity: "VS1",
    color: "H",
    cut: "Marquise",
    flourescence: "Faint",
    make: "Very Good",
    polish: "Good",
    symmetry: "Very Good",
    measurement: "7.5 - 5.0 x 3.0 mm",
    cert: "AGS",
    min_price: 6000,
    max_price: 6500,
    rap_percent: 9.5,
    rap_price: 6200,
    real_price: 6350,
    name: "AGS",
  },
  {
    id: 6,
    code: "CERT006",
    carat: 0.8,
    clarity: "SI2",
    color: "I",
    cut: "Cushion",
    flourescence: "None",
    make: "Good",
    polish: "Good",
    symmetry: "Good",
    measurement: "5.5 - 5.5 x 3.5 mm",
    cert: "GIA",
    min_price: 2500,
    max_price: 3000,
    rap_percent: 7.5,
    rap_price: 2700,
    real_price: 2850,
    name: "GIA",
  },
  {
    id: 7,
    code: "CERT007",
    carat: 1.3,
    clarity: "VVS2",
    color: "D",
    cut: "Asscher",
    flourescence: "Faint",
    make: "Excellent",
    polish: "Excellent",
    symmetry: "Excellent",
    measurement: "6.8 - 6.8 x 4.2 mm",
    cert: "IGI",
    min_price: 8000,
    max_price: 9000,
    rap_percent: 10.0,
    rap_price: 8500,
    real_price: 8700,
    name: "IGI",
  },
  {
    id: 8,
    code: "CERT008",
    carat: 1.6,
    clarity: "IF",
    color: "F",
    cut: "Radiant",
    flourescence: "None",
    make: "Very Good",
    polish: "Excellent",
    symmetry: "Very Good",
    measurement: "7.2 - 7.2 x 4.6 mm",
    cert: "HRD",
    min_price: 9500,
    max_price: 10500,
    rap_percent: 11.5,
    rap_price: 10000,
    real_price: 10250,
    name: "HRD",
  },
  {
    id: 9,
    code: "CERT009",
    carat: 2.2,
    clarity: "VS2",
    color: "G",
    cut: "Heart",
    flourescence: "Strong",
    make: "Good",
    polish: "Very Good",
    symmetry: "Good",
    measurement: "8.5 - 8.0 x 5.5 mm",
    cert: "GIA",
    min_price: 16000,
    max_price: 18000,
    rap_percent: 13.0,
    rap_price: 17000,
    real_price: 17500,
    name: "GIA",
  },
  {
    id: 10,
    code: "CERT010",
    carat: 1.4,
    clarity: "SI1",
    color: "H",
    cut: "Pear",
    flourescence: "None",
    make: "Very Good",
    polish: "Good",
    symmetry: "Very Good",
    measurement: "7.0 - 5.0 x 4.0 mm",
    cert: "AGS",
    min_price: 7000,
    max_price: 7500,
    rap_percent: 9.0,
    rap_price: 7200,
    real_price: 7400,
    name: "AGS",
  }
];
